<?php

use Illuminate\Database\Seeder;
use App\Parish;

class ParishesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $parishes = [
            ['id' => '1', 'name' => 'Bugyera', 'subcounty_id' => '1'],
            ['id' => '2', 'name' => 'Buyanja Town Board', 'subcounty_id' => '1'],
            ['id' => '3', 'name' => 'Kasheshe', 'subcounty_id' => '1'],
            ['id' => '4', 'name' => 'Kyamakanda', 'subcounty_id' => '1'],
            ['id' => '5', 'name' => 'Nyabitete', 'subcounty_id' => '1'],
            ['id' => '6', 'name' => 'Nyakaina', 'subcounty_id' => '1'],
            ['id' => '7', 'name' => 'Rubanga', 'subcounty_id' => '1'],
            ['id' => '8', 'name' => 'Rwakirungura', 'subcounty_id' => '1'],
            ['id' => '9', 'name' => 'Garubunda', 'subcounty_id' => '2'],
            ['id' => '10', 'name' => 'Kabingo', 'subcounty_id' => '2'],
            ['id' => '11', 'name' => 'Kakinga', 'subcounty_id' => '2'],
            ['id' => '12', 'name' => 'Karuhembe', 'subcounty_id' => '2'],
            ['id' => '13', 'name' => 'Kebisoni Town Board', 'subcounty_id' => '2'],
            ['id' => '14', 'name' => 'Kigiro', 'subcounty_id' => '2'],
            ['id' => '15', 'name' => 'Mabanga', 'subcounty_id' => '2'],
            ['id' => '16', 'name' => 'Nyeibingo', 'subcounty_id' => '2'],
            ['id' => '17', 'name' => 'Kacence', 'subcounty_id' => '3'],
            ['id' => '18', 'name' => 'Bikongozo', 'subcounty_id' => '3'],
            ['id' => '19', 'name' => 'Kafunjo, Nyakishenyi', 'subcounty_id' => '3'],
            ['id' => '20', 'name' => 'Kahoko', 'subcounty_id' => '3'],
            ['id' => '21', 'name' => 'Buhunga', 'subcounty_id' => '5'],
            ['id' => '22', 'name' => 'Bwanda', 'subcounty_id' => '5'],
            ['id' => '23', 'name' => 'Kabingo Buhunga', 'subcounty_id' => '5'],
            ['id' => '24', 'name' => 'Kibirizi', 'subcounty_id' => '5'],
            ['id' => '25', 'name' => 'Kihanga', 'subcounty_id' => '5'],
            ['id' => '26', 'name' => 'Karuyenje', 'subcounty_id' => '5'],
            ['id' => '27', 'name' => 'Bikurungu', 'subcounty_id' => '6'],
            ['id' => '28', 'name' => 'Bwambara', 'subcounty_id' => '6'],
            ['id' => '29', 'name' => 'Kikarara', 'subcounty_id' => '6'],
            ['id' => '30', 'name' => 'Kikongi', 'subcounty_id' => '6'],
            ['id' => '31', 'name' => 'Nyabubare', 'subcounty_id' => '6'],
            ['id' => '32', 'name' => 'Rwenshama', 'subcounty_id' => '6'],
            ['id' => '33', 'name' => 'Kabwooma', 'subcounty_id' => '7'],
            ['id' => '34', 'name' => 'Kahoko, Nyakagyeme', 'subcounty_id' => '7'],
            ['id' => '35', 'name' => 'Masya', 'subcounty_id' => '7'],
            ['id' => '36', 'name' => 'Nyakinengo', 'subcounty_id' => '7'],
            ['id' => '37', 'name' => 'Rushasha', 'subcounty_id' => '7'],
            ['id' => '38', 'name' => 'Rwerere', 'subcounty_id' => '7'],
            ['id' => '39', 'name' => 'Burombe', 'subcounty_id' => '8'],
            ['id' => '40', 'name' => 'Kicwamba', 'subcounty_id' => '8'],
            ['id' => '41', 'name' => 'Ndere', 'subcounty_id' => '8'],
            ['id' => '42', 'name' => 'Nyakitabire', 'subcounty_id' => '8'],
            ['id' => '43', 'name' => 'Nyarwimuka', 'subcounty_id' => '8'],
            ['id' => '44', 'name' => 'Katonya', 'subcounty_id' => '3'],
            ['id' => '45', 'name' => 'Murama', 'subcounty_id' => '3'],
            ['id' => '46', 'name' => 'Kagashe', 'subcounty_id' => '10'],
            ['id' => '47', 'name' => 'Kyatoko', 'subcounty_id' => '10'],
            ['id' => '48', 'name' => 'Rwentondo', 'subcounty_id' => '10'],
            ['id' => '49', 'name' => 'Kanyinya', 'subcounty_id' => '9'],
            ['id' => '50', 'name' => 'Kigaga', 'subcounty_id' => '10'],
            ['id' => '51', 'name' => 'Ndorero', 'subcounty_id' => '10'],
            ['id' => '52', 'name' => 'Rwakabengo', 'subcounty_id' => '10'],
            ['id' => '53', 'name' => 'Karangaro', 'subcounty_id' => '10'],
            ['id' => '54', 'name' => 'Kinyasano', 'subcounty_id' => '10'],
            ['id' => '55', 'name' => 'Kitimba', 'subcounty_id' => '10'],
            ['id' => '56', 'name' => 'Ngoma', 'subcounty_id' => '3'],
            ['id' => '57', 'name' => 'Nyarugando', 'subcounty_id' => '3'],
            ['id' => '58', 'name' => 'Rwanyundo', 'subcounty_id' => '3'],
            ['id' => '59', 'name' => 'Bonono', 'subcounty_id' => '4'],
            ['id' => '60', 'name' => 'Borora', 'subcounty_id' => '4'],
            ['id' => '61', 'name' => 'Bwanga', 'subcounty_id' => '4'],
            ['id' => '62', 'name' => 'Ibanda', 'subcounty_id' => '4'],
            ['id' => '63', 'name' => 'Ihunga', 'subcounty_id' => '4'],
            ['id' => '64', 'name' => 'Kisiizi', 'subcounty_id' => '4'],
            ['id' => '65', 'name' => 'Ndago', 'subcounty_id' => '4'],
            ['id' => '66', 'name' => 'Nyabushenyi', 'subcounty_id' => '4'],
            ['id' => '67', 'name' => 'Ruyonza', 'subcounty_id' => '4'],
            ['id' => '68', 'name' => 'Karangaro.', 'subcounty_id' => '12'],
            ['id' => '69', 'name' => 'Kinyasano.', 'subcounty_id' => '12'],
            ['id' => '70', 'name' => 'Kitimba.', 'subcounty_id' => '12'],
            ['id' => '71', 'name' => 'Rwamugoma', 'subcounty_id' => '13'],
            ['id' => '72', 'name' => 'Bugangari', 'subcounty_id' => '13'],
            ['id' => '73', 'name' => 'Burama', 'subcounty_id' => '13'],
            ['id' => '74', 'name' => 'Kakindo', 'subcounty_id' => '13'],
            ['id' => '75', 'name' => 'Kashayo', 'subcounty_id' => '13'],
            ['id' => '76', 'name' => 'Kazindiro', 'subcounty_id' => '13'],
            ['id' => '77', 'name' => 'Kyaburere', 'subcounty_id' => '13'],
            ['id' => '78', 'name' => 'Nyabitete Bugangari', 'subcounty_id' => '13'],
            ['id' => '79', 'name' => 'Kinoni', 'subcounty_id' => '14'],
            ['id' => '80', 'name' => 'Kiyaga', 'subcounty_id' => '14'],
            ['id' => '81', 'name' => 'Nkongoro', 'subcounty_id' => '14'],
            ['id' => '82', 'name' => 'Nyabushenyi Bwongyera', 'subcounty_id' => '14'],
            ['id' => '83', 'name' => 'Rukanga', 'subcounty_id' => '14'],
            ['id' => '84', 'name' => 'Rwashamaire', 'subcounty_id' => '14'],
            ['id' => '85', 'name' => 'Kagongi ', 'subcounty_id' => '18'],
            ['id' => '86', 'name' => 'Kakanena', 'subcounty_id' => '18'],
            ['id' => '87', 'name' => 'Katungamo', 'subcounty_id' => '18'],
            ['id' => '88', 'name' => 'Kyafoora', 'subcounty_id' => '18'],
            ['id' => '89', 'name' => 'Ngomba', 'subcounty_id' => '18'],
            ['id' => '90', 'name' => 'Nyakabungo', 'subcounty_id' => '18'],
            ['id' => '91', 'name' => 'Kashenyi', 'subcounty_id' => '20'],
            ['id' => '92', 'name' => 'Kiyanja', 'subcounty_id' => '20'],
            ['id' => '93', 'name' => 'Kizinga', 'subcounty_id' => '20'],
            ['id' => '94', 'name' => 'Mugyera', 'subcounty_id' => '20'],
            ['id' => '95', 'name' => 'Mukoni ', 'subcounty_id' => '20'],
            ['id' => '96', 'name' => 'Nyakariro ', 'subcounty_id' => '20'],
            ['id' => '97', 'name' => 'Ruhara', 'subcounty_id' => '20'],
            ['id' => '98', 'name' => 'Kagugu', 'subcounty_id' => '21'],
            ['id' => '99', 'name' => 'Mutojo', 'subcounty_id' => '21'],
            ['id' => '100', 'name' => 'Nyanga', 'subcounty_id' => '21'],
            ['id' => '101', 'name' => 'Nyarwanya', 'subcounty_id' => '21'],
            ['id' => '102', 'name' => 'Omugyenyi', 'subcounty_id' => '21'],
            ['id' => '103', 'name' => 'Rukira', 'subcounty_id' => '21'],
            ['id' => '104', 'name' => 'Butanda', 'subcounty_id' => '15'],
            ['id' => '105', 'name' => 'Kagamba', 'subcounty_id' => '15'],
            ['id' => '106', 'name' => 'Kitondo', 'subcounty_id' => '15'],
            ['id' => '107', 'name' => 'Kagarama Town Board', 'subcounty_id' => '15'],
            ['id' => '108', 'name' => 'Nyakibigi', 'subcounty_id' => '15'],
            ['id' => '109', 'name' => 'Rutunguru', 'subcounty_id' => '15'],
            ['id' => '110', 'name' => 'Ibaare', 'subcounty_id' => '16'],
            ['id' => '111', 'name' => 'Kanyampuumo', 'subcounty_id' => '16'],
            ['id' => '112', 'name' => 'Kibaruko', 'subcounty_id' => '16'],
            ['id' => '113', 'name' => 'Nyamugoye', 'subcounty_id' => '16'],
            ['id' => '114', 'name' => 'Nyamunuka Town Board', 'subcounty_id' => '16'],
            ['id' => '115', 'name' => 'Rukarango', 'subcounty_id' => '16'],
            ['id' => '116', 'name' => 'Rukoni', 'subcounty_id' => '16'],
            ['id' => '117', 'name' => 'Central Ward', 'subcounty_id' => '19'],
            ['id' => '118', 'name' => 'Kikoni', 'subcounty_id' => '19'],
            ['id' => '119', 'name' => 'Kyamate Ward', 'subcounty_id' => '22'],
            ['id' => '120', 'name' => 'Park Yard', 'subcounty_id' => '22'],
            ['id' => '121', 'name' => 'Kahunga Ward', 'subcounty_id' => '23'],
            ['id' => '122', 'name' => 'Muko Ward', 'subcounty_id' => '23'],
            ['id' => '123', 'name' => 'Iterero', 'subcounty_id' => '17'],
            ['id' => '124', 'name' => 'Kakiika', 'subcounty_id' => '17'],
            ['id' => '125', 'name' => 'Katomi', 'subcounty_id' => '17'],
            ['id' => '126', 'name' => 'Kitojo', 'subcounty_id' => '17'],
            ['id' => '127', 'name' => 'Kabashenyi', 'subcounty_id' => '17'],
            ['id' => '128', 'name' => 'Kyaruhuga', 'subcounty_id' => '17'],
            ['id' => '129', 'name' => 'Nyabubare, Nyabihoko', 'subcounty_id' => '17'],
            ['id' => '130', 'name' => 'Rwanda', 'subcounty_id' => '17'],
            ['id' => '131', 'name' => 'Kijuguta', 'subcounty_id' => '25'],
            ['id' => '132', 'name' => 'Lower Bugongi', 'subcounty_id' => '25'],
            ['id' => '133', 'name' => 'Rutooma', 'subcounty_id' => '25'],
            ['id' => '134', 'name' => 'Upper Bugongi', 'subcounty_id' => '25'],
            ['id' => '135', 'name' => 'Karubanda', 'subcounty_id' => '24'],
            ['id' => '136', 'name' => 'Kirigime', 'subcounty_id' => '24'],
            ['id' => '137', 'name' => 'Mwanjari', 'subcounty_id' => '24'],
            ['id' => '138', 'name' => 'Rushaki', 'subcounty_id' => '24'],
            ['id' => '139', 'name' => 'Butobere', 'subcounty_id' => '26'],
            ['id' => '140', 'name' => 'Butobere', 'subcounty_id' => '26'],
            ['id' => '141', 'name' => 'Butobere', 'subcounty_id' => '26'],
            ['id' => '142', 'name' => 'Butobere', 'subcounty_id' => '26'],
            ['id' => '143', 'name' => 'Butobere', 'subcounty_id' => '26'],
            ['id' => '144', 'name' => 'Kabele Central', 'subcounty_id' => '26'],
            ['id' => '145', 'name' => 'Kabale Central', 'subcounty_id' => '26'],
            ['id' => '146', 'name' => 'Kigongi Ward', 'subcounty_id' => '26'],
            ['id' => '147', 'name' => 'Nyabikoni', 'subcounty_id' => '26'],
            ['id' => '148', 'name' => 'Kyabashenyi', 'subcounty_id' => '17'],
            ['id' => '149', 'name' => 'Ahamurambi', 'subcounty_id' => '27'],
            ['id' => '150', 'name' => 'Kandago', 'subcounty_id' => '27'],
            ['id' => '151', 'name' => 'Karorwa', 'subcounty_id' => '27'],
            ['id' => '152', 'name' => 'Muhanga', 'subcounty_id' => '27'],
            ['id' => '153', 'name' => 'Nyabirerema', 'subcounty_id' => '27'],
            ['id' => '154', 'name' => 'Nyakasiru', 'subcounty_id' => '27'],
            ['id' => '155', 'name' => 'Buhanama', 'subcounty_id' => '31'],
            ['id' => '156', 'name' => 'Itojo', 'subcounty_id' => '31'],
            ['id' => '157', 'name' => 'Nyongozi', 'subcounty_id' => '31'],
            ['id' => '158', 'name' => 'Ruhanga', 'subcounty_id' => '31'],
            ['id' => '159', 'name' => 'Butare', 'subcounty_id' => '32'],
            ['id' => '160', 'name' => 'Kahunga', 'subcounty_id' => '32'],
            ['id' => '161', 'name' => 'Kikoni Ntungamo', 'subcounty_id' => '32'],
            ['id' => '162', 'name' => 'Kizaara', 'subcounty_id' => '32'],
            ['id' => '163', 'name' => 'Nyaburiza', 'subcounty_id' => '32'],
            ['id' => '164', 'name' => 'Nyarubare', 'subcounty_id' => '32'],
            ['id' => '165', 'name' => 'Ruhoko', 'subcounty_id' => '32'],
            ['id' => '166', 'name' => 'Kagorogoro', 'subcounty_id' => '33'],
            ['id' => '167', 'name' => 'Kataraka', 'subcounty_id' => '33'],
            ['id' => '168', 'name' => 'Kibingo', 'subcounty_id' => '33'],
            ['id' => '169', 'name' => 'Kiyoora', 'subcounty_id' => '33'],
            ['id' => '170', 'name' => 'Kiziba', 'subcounty_id' => '33'],
            ['id' => '171', 'name' => 'Ngoma.', 'subcounty_id' => '33'],
            ['id' => '172', 'name' => 'Ngomba.', 'subcounty_id' => '33'],
            ['id' => '173', 'name' => 'Kafunjo, Ruhaama', 'subcounty_id' => '34'],
            ['id' => '174', 'name' => 'Katojo, Ruhaama', 'subcounty_id' => '34'],
            ['id' => '175', 'name' => 'Kishami', 'subcounty_id' => '34'],
            ['id' => '176', 'name' => 'Kyagwehinde', 'subcounty_id' => '34'],
            ['id' => '177', 'name' => 'Ruhaama', 'subcounty_id' => '34'],
            ['id' => '178', 'name' => 'Rwamwire', 'subcounty_id' => '34'],
            ['id' => '179', 'name' => 'Rwengoma', 'subcounty_id' => '34'],
            ['id' => '180', 'name' => 'Kihanga, Rukoni', 'subcounty_id' => '36'],
            ['id' => '181', 'name' => 'kirungu', 'subcounty_id' => '36'],
            ['id' => '182', 'name' => 'Kitojo.', 'subcounty_id' => '36'],
            ['id' => '183', 'name' => 'Kyamwasha', 'subcounty_id' => '36'],
            ['id' => '184', 'name' => 'Rwoho', 'subcounty_id' => '36'],
            ['id' => '185', 'name' => 'Kitwe', 'subcounty_id' => '36'],
            ['id' => '186', 'name' => 'Nshenyi', 'subcounty_id' => '36'],
            ['id' => '187', 'name' => 'Nyakabaare', 'subcounty_id' => '36'],
            ['id' => '188', 'name' => 'Rukoni.', 'subcounty_id' => '36'],
            ['id' => '189', 'name' => 'Kirungu.', 'subcounty_id' => '35'],
            ['id' => '190', 'name' => 'Kitojo..', 'subcounty_id' => '35'],
            ['id' => '191', 'name' => 'Kyamwasha.', 'subcounty_id' => '35'],
            ['id' => '192', 'name' => 'Bwoho.', 'subcounty_id' => '35'],
            ['id' => '193', 'name' => 'Kihanga..', 'subcounty_id' => '35'],
            ['id' => '194', 'name' => 'Kabungo', 'subcounty_id' => '37'],
            ['id' => '195', 'name' => 'Kayenje', 'subcounty_id' => '37'],
            ['id' => '196', 'name' => 'Kitashekwa', 'subcounty_id' => '37'],
            ['id' => '197', 'name' => 'Murambi', 'subcounty_id' => '37'],
            ['id' => '198', 'name' => 'Rushebeya', 'subcounty_id' => '37'],
            ['id' => '199', 'name' => 'kabasheshe', 'subcounty_id' => '38'],
            ['id' => '200', 'name' => 'Kaina', 'subcounty_id' => '38'],
            ['id' => '201', 'name' => 'Katooma', 'subcounty_id' => '38'],
            ['id' => '202', 'name' => 'Kijubwe', 'subcounty_id' => '38'],
            ['id' => '203', 'name' => 'Kyobwe', 'subcounty_id' => '38'],
            ['id' => '204', 'name' => 'Ruhega', 'subcounty_id' => '38'],
            ['id' => '205', 'name' => 'Bugongi, Kambuga', 'subcounty_id' => '39'],
            ['id' => '206', 'name' => 'katete', 'subcounty_id' => '39'],
            ['id' => '207', 'name' => 'Kiringa', 'subcounty_id' => '39'],
            ['id' => '208', 'name' => 'Nyarugunda', 'subcounty_id' => '39'],
            ['id' => '209', 'name' => 'Nyarutojo', 'subcounty_id' => '39'],
            ['id' => '210', 'name' => 'Ruhandagazi', 'subcounty_id' => '39'],
            ['id' => '211', 'name' => 'Eastern Ward Kanungu T/C', 'subcounty_id' => '40'],
            ['id' => '212', 'name' => 'Northern Ward Kanungu T/C', 'subcounty_id' => '40'],
            ['id' => '213', 'name' => 'Southern Ward Kanungu T/C', 'subcounty_id' => '40'],
            ['id' => '214', 'name' => 'Western Ward Kanungu T/C', 'subcounty_id' => '40'],
            ['id' => '215', 'name' => 'Burema', 'subcounty_id' => '41'],
            ['id' => '216', 'name' => 'Kihembe', 'subcounty_id' => '41'],
            ['id' => '217', 'name' => 'Kishenyi', 'subcounty_id' => '41'],
            ['id' => '218', 'name' => 'Nyamigoye', 'subcounty_id' => '41'],
            ['id' => '219', 'name' => 'Bujengwe', 'subcounty_id' => '42'],
            ['id' => '220', 'name' => 'Karangara', 'subcounty_id' => '42'],
            ['id' => '221', 'name' => 'Kyeshero', 'subcounty_id' => '42'],
            ['id' => '222', 'name' => 'Mukono', 'subcounty_id' => '42'],
            ['id' => '223', 'name' => 'Ntungamo', 'subcounty_id' => '42'],
            ['id' => '224', 'name' => 'Kambuga', 'subcounty_id' => '43'],
            ['id' => '225', 'name' => 'Karubeizi', 'subcounty_id' => '43'],
            ['id' => '226', 'name' => 'Kibimbiri', 'subcounty_id' => '43'],
            ['id' => '227', 'name' => 'Nkunda', 'subcounty_id' => '43'],
            ['id' => '228', 'name' => 'Nyanga.', 'subcounty_id' => '43'],
            ['id' => '229', 'name' => 'Rushoroza', 'subcounty_id' => '43'],
            ['id' => '230', 'name' => 'Samaria', 'subcounty_id' => '43'],
            ['id' => '231', 'name' => 'Kihihi Town Board', 'subcounty_id' => '44'],
            ['id' => '232', 'name' => 'Nyakatunguru', 'subcounty_id' => '44'],
            ['id' => '233', 'name' => 'Rwanda.', 'subcounty_id' => '44'],
            ['id' => '234', 'name' => 'Rwanga', 'subcounty_id' => '44'],
            ['id' => '235', 'name' => 'Bushura', 'subcounty_id' => '45'],
            ['id' => '236', 'name' => 'Kihanda', 'subcounty_id' => '45'],
            ['id' => '237', 'name' => 'Rubimbwa', 'subcounty_id' => '45'],
            ['id' => '238', 'name' => 'Rutugunda', 'subcounty_id' => '45'],
            ['id' => '239', 'name' => 'Buremba', 'subcounty_id' => '46'],
            ['id' => '240', 'name' => 'Mpungu', 'subcounty_id' => '46'],
            ['id' => '241', 'name' => 'Muramba', 'subcounty_id' => '46'],
            ['id' => '242', 'name' => 'Ngara', 'subcounty_id' => '46'],
            ['id' => '243', 'name' => 'Kigarama', 'subcounty_id' => '47'],
            ['id' => '244', 'name' => 'Mashaku', 'subcounty_id' => '47'],
            ['id' => '245', 'name' => 'Ntungwa', 'subcounty_id' => '47'],
            ['id' => '246', 'name' => 'Nyakashure', 'subcounty_id' => '47'],
            ['id' => '247', 'name' => 'Nyarurambi, Nyamirama', 'subcounty_id' => '47'],
            ['id' => '248', 'name' => 'Rushaka', 'subcounty_id' => '47'],
            ['id' => '249', 'name' => 'kashojwa', 'subcounty_id' => '48'],
            ['id' => '250', 'name' => 'Katungu', 'subcounty_id' => '48'],
            ['id' => '251', 'name' => 'kayungwe', 'subcounty_id' => '48'],
            ['id' => '252', 'name' => 'Kitojo, Rugyeyo', 'subcounty_id' => '48'],
            ['id' => '253', 'name' => 'Mishenyi', 'subcounty_id' => '48'],
            ['id' => '254', 'name' => 'Nyarurambi, Rugyeyo', 'subcounty_id' => '48'],
            ['id' => '255', 'name' => 'katojo.', 'subcounty_id' => '49'],
            ['id' => '256', 'name' => 'Kinaba', 'subcounty_id' => '49'],
            ['id' => '257', 'name' => 'Mafuga', 'subcounty_id' => '49'],
            ['id' => '258', 'name' => 'Muramba, Rutenga', 'subcounty_id' => '49'],
            ['id' => '259', 'name' => 'Bucundura', 'subcounty_id' => '29'],
            ['id' => '260', 'name' => 'Kitanga', 'subcounty_id' => '29'],
            ['id' => '261', 'name' => 'Kitunga', 'subcounty_id' => '29'],
            ['id' => '262', 'name' => 'Nyakashebeya', 'subcounty_id' => '29'],
            ['id' => '263', 'name' => 'Rutengye', 'subcounty_id' => '29'],
            ['id' => '264', 'name' => 'Kafunjo, Kashambya', 'subcounty_id' => '29'],
            ['id' => '265', 'name' => 'Burime', 'subcounty_id' => '30'],
            ['id' => '266', 'name' => 'Ibumba', 'subcounty_id' => '30'],
            ['id' => '267', 'name' => 'Mparo', 'subcounty_id' => '30'],
            ['id' => '268', 'name' => 'Noozi', 'subcounty_id' => '30'],
            ['id' => '269', 'name' => 'Nyakagabagaba', 'subcounty_id' => '30'],
            ['id' => '270', 'name' => 'Nyarurambi, Rwamucucu', 'subcounty_id' => '30'],
            ['id' => '271', 'name' => 'Kashekye', 'subcounty_id' => '28'],
            ['id' => '272', 'name' => 'Kibanda', 'subcounty_id' => '28'],
            ['id' => '273', 'name' => 'Kigara', 'subcounty_id' => '28'],
            ['id' => '274', 'name' => 'Kyabuhangwa', 'subcounty_id' => '28'],
            ['id' => '275', 'name' => 'Kyogo', 'subcounty_id' => '28'],
            ['id' => '276', 'name' => 'Rwenyangye', 'subcounty_id' => '28'],
            ['id' => '277', 'name' => 'Kyanjobe', 'subcounty_id' => '49'],
            ['id' => '278', 'name' => 'Kofunjo', 'subcounty_id' => '4'],
            ['id' => '279', 'name' => 'Nyakibare', 'subcounty_id' => '9'],
            ['id' => '280', 'name' => 'Mpungu Hamurwa', 'subcounty_id' => '50'],
            ['id' => '281', 'name' => 'Kagunga', 'subcounty_id' => '12'],
            ['id' => '282', 'name' => 'Kinamo', 'subcounty_id' => '53'],
            ['id' => '283', 'name' => 'Kigaga Ward', 'subcounty_id' => '11'],
            ['id' => '284', 'name' => 'Katojo', 'subcounty_id' => '14'],
            ['id' => '285', 'name' => 'Kiyebe', 'subcounty_id' => '54'],
            ['id' => '286', 'name' => 'Kikoba', 'subcounty_id' => '55'],
            ['id' => '287', 'name' => 'RWAMUJURA', 'subcounty_id' => '56'],
            ['id' => '288', 'name' => 'KYANTUHE', 'subcounty_id' => '47'],
            ['id' => '289', 'name' => 'Rurehe', 'subcounty_id' => '60'],
            ['id' => '290', 'name' => 'rutenga', 'subcounty_id' => '57'],
            ['id' => '291', 'name' => 'kyatoko', 'subcounty_id' => '61'],
            ['id' => '292', 'name' => 'Karukonjo', 'subcounty_id' => '3'],
            ['id' => '293', 'name' => 'ngomba', 'subcounty_id' => '63'],
            ['id' => '294', 'name' => 'Muhanga', 'subcounty_id' => '64'],
            ['id' => '295', 'name' => 'Burora', 'subcounty_id' => '4'],
            ['id' => '296', 'name' => 'Kabimbiri road', 'subcounty_id' => '65'],
            ['id' => '297', 'name' => 'Kabimbiri Ward', 'subcounty_id' => '65'],
            ['id' => '298', 'name' => 'Nyakabungo', 'subcounty_id' => '66'],
            ['id' => '299', 'name' => 'Bugarama', 'subcounty_id' => '67'],
            ['id' => '300', 'name' => 'Nyabushenyi', 'subcounty_id' => '17'],
            ['id' => '301', 'name' => 'Ngomanda', 'subcounty_id' => '50'],
            ['id' => '302', 'name' => 'Nyakabungo, Buyanja', 'subcounty_id' => '1'],
            ['id' => '303', 'name' => 'Kasaana', 'subcounty_id' => '18'],
            ['id' => '304', 'name' => 'RWANJA', 'subcounty_id' => '68'],
            ['id' => '305', 'name' => 'Nyakagyera', 'subcounty_id' => '69'],
            ['id' => '306', 'name' => 'Muyumbu', 'subcounty_id' => '69'],
            ['id' => '307', 'name' => 'Nyabushabi', 'subcounty_id' => '69'],
            ['id' => '308', 'name' => 'Kigata', 'subcounty_id' => '69'],
            ['id' => '309', 'name' => 'Kyanamira', 'subcounty_id' => '69'],
            ['id' => '310', 'name' => 'Katookye', 'subcounty_id' => '69'],
            ['id' => '311', 'name' => 'Kanjobe', 'subcounty_id' => '69'],
            ['id' => '312', 'name' => 'Kafunjo', 'subcounty_id' => '29'],
            ['id' => '313', 'name' => 'Kanimi', 'subcounty_id' => '70'],
            ['id' => '314', 'name' => 'Nangara', 'subcounty_id' => '71'],
            ['id' => '315', 'name' => 'NYAKABUNGO', 'subcounty_id' => '48'],
            ['id' => '316', 'name' => 'kisiizi', 'subcounty_id' => '3'],
            ['id' => '317', 'name' => 'Bubaare', 'subcounty_id' => '73'],
            ['id' => '318', 'name' => 'Kitanga', 'subcounty_id' => '76'],
            ['id' => '319', 'name' => 'Bisozi', 'subcounty_id' => '77'],
            ['id' => '320', 'name' => 'Bunono', 'subcounty_id' => '4'],
            ['id' => '321', 'name' => 'Butagasi', 'subcounty_id' => '12'],
            ['id' => '322', 'name' => 'Rukanga', 'subcounty_id' => '17'],
            ['id' => '323', 'name' => 'Rushebeya', 'subcounty_id' => '30'],
            ['id' => '324', 'name' => 'Kitojo Rwamucucu', 'subcounty_id' => '30'],
            ['id' => '325', 'name' => 'Mwizi', 'subcounty_id' => '78'],
            ['id' => '326', 'name' => 'Kiniogo ward', 'subcounty_id' => '79'],
            ['id' => '327', 'name' => 'Ntungu', 'subcounty_id' => '80'],
            ['id' => '328', 'name' => 'Bwoma', 'subcounty_id' => '61'],
            ['id' => '329', 'name' => 'Bwoma', 'subcounty_id' => '75'],
            ['id' => '330', 'name' => 'Wabusaana', 'subcounty_id' => '82'],
            ['id' => '331', 'name' => 'Kyabukuju', 'subcounty_id' => '21'],
            ['id' => '332', 'name' => 'Kyabukuju', 'subcounty_id' => '73'],
            ['id' => '333', 'name' => 'Rwanja', 'subcounty_id' => '56'],
            ['id' => '334', 'name' => 'Omukibare', 'subcounty_id' => '34'],
            ['id' => '335', 'name' => 'Omukibare', 'subcounty_id' => '65'],
            ['id' => '336', 'name' => 'Southern Division', 'subcounty_id' => '11'],
            ['id' => '337', 'name' => 'Kagango', 'subcounty_id' => '21'],
            ['id' => '338', 'name' => 'Rwanda Bwongyera', 'subcounty_id' => '14'],
            ['id' => '339', 'name' => 'Kyaruhuga Bwongyera', 'subcounty_id' => '14'],
            ['id' => '340', 'name' => 'Kitimba', 'subcounty_id' => '7'],
            ['id' => '341', 'name' => 'Nshenyi', 'subcounty_id' => '65'],
            ['id' => '342', 'name' => 'Nshenyi', 'subcounty_id' => '86'],
            ['id' => '343', 'name' => 'Engaju', 'subcounty_id' => '87'],
            ['id' => '344', 'name' => 'Kafunjo', 'subcounty_id' => '4'],
            ['id' => '345', 'name' => 'Kakiika', 'subcounty_id' => '14'],
            ['id' => '346', 'name' => 'Katomi', 'subcounty_id' => '14'],
            ['id' => '347', 'name' => 'Kyerero', 'subcounty_id' => '27'],
            ['id' => '348', 'name' => 'Kishanje', 'subcounty_id' => '88'],
            ['id' => '349', 'name' => 'Bitooma', 'subcounty_id' => '89'],
            ['id' => '350', 'name' => 'Kigaaga', 'subcounty_id' => '7'],
            ['id' => '351', 'name' => 'Rwentonda', 'subcounty_id' => '61'],
            ['id' => '352', 'name' => 'Nyabihinga', 'subcounty_id' => '61'],
            ['id' => '353', 'name' => 'Katenga', 'subcounty_id' => '67'],
            ['id' => '354', 'name' => 'Migamba', 'subcounty_id' => '91'],
            ['id' => '355', 'name' => 'Bweza', 'subcounty_id' => '93'],
            ['id' => '356', 'name' => 'Nyakabare', 'subcounty_id' => '35'],
            ['id' => '357', 'name' => 'Kataraza', 'subcounty_id' => '94'],
            ['id' => '358', 'name' => 'Nkunda', 'subcounty_id' => '95'],
            ['id' => '359', 'name' => 'Iterero Bwongyera', 'subcounty_id' => '14'],
            ['id' => '360', 'name' => 'Southern Ward', 'subcounty_id' => '96'],
            ['id' => '361', 'name' => 'chine', 'subcounty_id' => '97'],
            ['id' => '362', 'name' => 'Kisaluwoko', 'subcounty_id' => '98'],
            ['id' => '363', 'name' => 'Western  ward', 'subcounty_id' => '99'],
            ['id' => '364', 'name' => 'Kayanja', 'subcounty_id' => '101'],
            ['id' => '365', 'name' => 'Rwakabengo Ward', 'subcounty_id' => '11'],
            ['id' => '366', 'name' => 'Kyabashenyi Bwongyera', 'subcounty_id' => '14'],
            ['id' => '367', 'name' => 'Byengyerero', 'subcounty_id' => '68'],
            ['id' => '368', 'name' => 'Kiyonga', 'subcounty_id' => '103'],
            ['id' => '369', 'name' => 'Rwamugoma', 'subcounty_id' => '8'],
            ['id' => '370', 'name' => 'Kiyaga', 'subcounty_id' => '17'],
            ['id' => '371', 'name' => 'Rwanyadere', 'subcounty_id' => '104'],
            ['id' => '372', 'name' => 'Kyentama', 'subcounty_id' => '65'],
            ['id' => '373', 'name' => 'Mayanga', 'subcounty_id' => '56'],
            ['id' => '374', 'name' => 'Kyidokoli', 'subcounty_id' => '105'],
            ['id' => '375', 'name' => 'Kijoha', 'subcounty_id' => '106'],
            ['id' => '376', 'name' => 'Rutare Ward', 'subcounty_id' => '111'],
            ['id' => '377', 'name' => 'Rwenshuri', 'subcounty_id' => '112'],
            ['id' => '378', 'name' => 'Mutambuka', 'subcounty_id' => '26'],
            ['id' => '379', 'name' => 'Kyonyo', 'subcounty_id' => '79'],
            ['id' => '380', 'name' => 'Kyonyo', 'subcounty_id' => '79'],
            ['id' => '381', 'name' => 'Kamuri', 'subcounty_id' => '113'],
            ['id' => '382', 'name' => 'NDIIJA', 'subcounty_id' => '115'],
            ['id' => '383', 'name' => 'NDIIJA', 'subcounty_id' => '115'],
            ['id' => '384', 'name' => 'Kagarama', 'subcounty_id' => '81'],
            ['id' => '385', 'name' => 'Kashasha', 'subcounty_id' => '117'],
            ['id' => '386', 'name' => 'Kyezimbire', 'subcounty_id' => '118'],
            ['id' => '387', 'name' => 'Karera', 'subcounty_id' => '119'],
            ['id' => '388', 'name' => 'Karera', 'subcounty_id' => '119'],
            ['id' => '389', 'name' => 'Karera', 'subcounty_id' => '119'],
            ['id' => '390', 'name' => 'Katwekamwe', 'subcounty_id' => '10'],
            ['id' => '391', 'name' => 'Katunda', 'subcounty_id' => '120'],
            ['id' => '392', 'name' => 'Katunda', 'subcounty_id' => '120'],
            ['id' => '393', 'name' => 'RWASHAMIRE', 'subcounty_id' => '122'],
            ['id' => '394', 'name' => 'RWASHAMIRE TC', 'subcounty_id' => '122'],
            ['id' => '395', 'name' => 'Kyandahi', 'subcounty_id' => '123'],
            ['id' => '396', 'name' => 'Kyandahi', 'subcounty_id' => '6'],
            ['id' => '397', 'name' => 'Kyandahi', 'subcounty_id' => '124'],
            ['id' => '398', 'name' => 'Kashasha  Ikumba', 'subcounty_id' => '107'],
            ['id' => '399', 'name' => 'Kimwani w', 'subcounty_id' => '122'],
            ['id' => '400', 'name' => 'Rwamwijuka', 'subcounty_id' => '118'],
            ['id' => '401', 'name' => 'Rwamwijuka', 'subcounty_id' => '118'],
            ['id' => '402', 'name' => 'Bwera', 'subcounty_id' => '126'],
            ['id' => '403', 'name' => 'Rwakakwenda', 'subcounty_id' => '127'],
            ['id' => '404', 'name' => 'Kabugu', 'subcounty_id' => '127'],
            ['id' => '405', 'name' => 'Nyakatoma', 'subcounty_id' => '128'],
            ['id' => '406', 'name' => 'Kashekuro', 'subcounty_id' => '129'],
            ['id' => '407', 'name' => 'Park word', 'subcounty_id' => '23'],
            ['id' => '408', 'name' => 'Nungamo Park Ward', 'subcounty_id' => '23'],
            ['id' => '409', 'name' => 'Rushando ward', 'subcounty_id' => '112'],
            ['id' => '410', 'name' => 'Rugarama', 'subcounty_id' => '130'],
            ['id' => '411', 'name' => 'Rutaraka', 'subcounty_id' => '73'],
            ['id' => '412', 'name' => 'Rutaraka', 'subcounty_id' => '90'],
            ['id' => '413', 'name' => 'Rukarabo', 'subcounty_id' => '78'],
            ['id' => '414', 'name' => 'Kahondo', 'subcounty_id' => '130'],
            ['id' => '415', 'name' => 'Rugazi', 'subcounty_id' => '131'],
            ['id' => '416', 'name' => 'Nyakahita', 'subcounty_id' => '104'],
            ['id' => '417', 'name' => 'Nyanseke Ward', 'subcounty_id' => '132'],
            ['id' => '418', 'name' => 'Nkongoro Nyabihoko', 'subcounty_id' => '17'],
            ['id' => '419', 'name' => 'Rwemitago', 'subcounty_id' => '133'],
            ['id' => '420', 'name' => 'Nyakabungu', 'subcounty_id' => '18'],
            ['id' => '421', 'name' => 'kabirizi', 'subcounty_id' => '21'],
            ['id' => '422', 'name' => 'Kiziba', 'subcounty_id' => '137'],
            ['id' => '423', 'name' => 'Rutuguru', 'subcounty_id' => '15'],
            ['id' => '424', 'name' => 'Rutuguru', 'subcounty_id' => '15'],
            ['id' => '425', 'name' => 'Rutuguru', 'subcounty_id' => '15'],
            ['id' => '426', 'name' => 'Rutuguru', 'subcounty_id' => '15'],
            ['id' => '427', 'name' => 'Rutuguru', 'subcounty_id' => '15'],
            ['id' => '428', 'name' => 'Rutuguru', 'subcounty_id' => '15'],
            ['id' => '429', 'name' => 'Ruhuguru', 'subcounty_id' => '15'],
            ['id' => '430', 'name' => 'Rukiri', 'subcounty_id' => '21'],
            ['id' => '431', 'name' => 'Nyakarambi', 'subcounty_id' => '80'],
            ['id' => '432', 'name' => 'Nyakarambi', 'subcounty_id' => '80'],
            ['id' => '433', 'name' => 'Kabanzi', 'subcounty_id' => '6'],
            ['id' => '434', 'name' => 'Ndorero Ward', 'subcounty_id' => '11'],
            ['id' => '435', 'name' => 'Kirimbi', 'subcounty_id' => '3'],
            ['id' => '436', 'name' => 'Katonto', 'subcounty_id' => '3'],
            ['id' => '437', 'name' => 'Kanywamaizi', 'subcounty_id' => '127'],
            ['id' => '438', 'name' => 'Kitojo Bwongyera', 'subcounty_id' => '14'],
            ['id' => '439', 'name' => 'Biguri', 'subcounty_id' => '142'],
            ['id' => '440', 'name' => 'Rwongora', 'subcounty_id' => '30'],
            ['id' => '441', 'name' => 'kakamba', 'subcounty_id' => '144'],
            ['id' => '442', 'name' => 'Kakamba.', 'subcounty_id' => '144'],
            ['id' => '443', 'name' => 'Butogota Town Concil', 'subcounty_id' => '96'],
            ['id' => '444', 'name' => 'Kateete', 'subcounty_id' => '101'],
            ['id' => '445', 'name' => 'Nyaburiza', 'subcounty_id' => '139'],
            ['id' => '446', 'name' => 'Iryango Ward', 'subcounty_id' => '127'],
            ['id' => '447', 'name' => 'Nyakazinga', 'subcounty_id' => '104'],
            ['id' => '448', 'name' => 'RUGOHO', 'subcounty_id' => '35'],
            ['id' => '449', 'name' => 'Nyabubare', 'subcounty_id' => '59'],
            ['id' => '450', 'name' => 'Nyabubare', 'subcounty_id' => '60'],
            ['id' => '451', 'name' => 'Kakoba', 'subcounty_id' => '147'],
            ['id' => '452', 'name' => 'Central Ward', 'subcounty_id' => '65'],
            ['id' => '453', 'name' => 'Keichumu', 'subcounty_id' => '148'],
            ['id' => '454', 'name' => 'Keihangare', 'subcounty_id' => '149'],
            ['id' => '455', 'name' => 'Nyarurambi', 'subcounty_id' => '101'],
            ['id' => '456', 'name' => 'Kitoha', 'subcounty_id' => '67'],
            ['id' => '457', 'name' => 'Karwenyi', 'subcounty_id' => '150'],
            ['id' => '458', 'name' => 'Kakiri', 'subcounty_id' => '151'],
            ['id' => '459', 'name' => 'Rumuri', 'subcounty_id' => '131'],
            ['id' => '460', 'name' => 'Mushanje', 'subcounty_id' => '107'],
            ['id' => '461', 'name' => 'Kyankukwe', 'subcounty_id' => '121'],
            ['id' => '462', 'name' => 'Rwenkuba', 'subcounty_id' => '152'],
            ['id' => '463', 'name' => 'kibare', 'subcounty_id' => '104'],
            ['id' => '464', 'name' => 'Kitojo', 'subcounty_id' => '73'],
            ['id' => '465', 'name' => 'kataara', 'subcounty_id' => '154'],
            ['id' => '466', 'name' => 'katara', 'subcounty_id' => '153'],
            ['id' => '467', 'name' => 'Nyamabare', 'subcounty_id' => '107'],
            ['id' => '468', 'name' => 'Syoro', 'subcounty_id' => '127'],
            ['id' => '469', 'name' => 'Kagango', 'subcounty_id' => '156'],
            ['id' => '470', 'name' => 'Mukakabada', 'subcounty_id' => '12'],
            ['id' => '471', 'name' => 'Kagamba', 'subcounty_id' => '122'],
            ['id' => '472', 'name' => 'Bwindi', 'subcounty_id' => '71'],
            ['id' => '473', 'name' => 'Ruhega', 'subcounty_id' => '18'],
            ['id' => '474', 'name' => 'Kanyampumo', 'subcounty_id' => '17'],
            ['id' => '475', 'name' => 'Karujanga', 'subcounty_id' => '157'],
            ['id' => '476', 'name' => 'Rubare', 'subcounty_id' => '158'],
            ['id' => '477', 'name' => 'Taryama', 'subcounty_id' => '160'],
            ['id' => '478', 'name' => 'Kitwe Central Ward', 'subcounty_id' => '65'],
            ['id' => '479', 'name' => 'Rushasha', 'subcounty_id' => '163'],
            ['id' => '480', 'name' => 'Kyenyi', 'subcounty_id' => '164'],
            ['id' => '481', 'name' => 'Nyaburiza', 'subcounty_id' => '37'],
            ['id' => '482', 'name' => 'Kigorani', 'subcounty_id' => '165'],
            ['id' => '483', 'name' => 'Nyabubare-bwongyera', 'subcounty_id' => '14'],
            ['id' => '484', 'name' => 'Mbogo', 'subcounty_id' => '166'],
            ['id' => '485', 'name' => 'kakanena', 'subcounty_id' => '66'],
            ['id' => '486', 'name' => 'kakanena', 'subcounty_id' => '134'],
            ['id' => '487', 'name' => 'Rukungiri', 'subcounty_id' => '167'],
            ['id' => '488', 'name' => 'Kitunguru', 'subcounty_id' => '168'],
            ['id' => '489', 'name' => 'Kyampango', 'subcounty_id' => '169'],
            ['id' => '490', 'name' => 'Kyambogo', 'subcounty_id' => '171'],
            ['id' => '491', 'name' => 'Kamukuzi', 'subcounty_id' => '172'],
            ['id' => '492', 'name' => 'kakyera', 'subcounty_id' => '172'],
            ['id' => '493', 'name' => 'Nyakagyera', 'subcounty_id' => '39'],
            ['id' => '494', 'name' => 'Kitwe', 'subcounty_id' => '173'],
            ['id' => '495', 'name' => 'Buranga', 'subcounty_id' => '174'],
            ['id' => '496', 'name' => 'Bwagonga', 'subcounty_id' => '166'],
            ['id' => '497', 'name' => 'Kasozi central', 'subcounty_id' => '119'],
            ['id' => '498', 'name' => 'Kitojo', 'subcounty_id' => '175'],
            ['id' => '499', 'name' => 'Rwanda', 'subcounty_id' => '14'],
            ['id' => '500', 'name' => 'Omukirago', 'subcounty_id' => '1'],
            ['id' => '501', 'name' => 'Rutoma', 'subcounty_id' => '176'],
            ['id' => '502', 'name' => 'Kati', 'subcounty_id' => '126'],
            ['id' => '503', 'name' => 'Katonjo', 'subcounty_id' => '3'],
            ['id' => '504', 'name' => 'Burebane', 'subcounty_id' => '45'],
            ['id' => '505', 'name' => 'Nyakahama', 'subcounty_id' => '152'],
            ['id' => '506', 'name' => 'Gabarungi Ward', 'subcounty_id' => '177'],
            ['id' => '507', 'name' => 'Kirera', 'subcounty_id' => '128'],
            ['id' => '508', 'name' => 'Kagarama', 'subcounty_id' => '178'],
            ['id' => '509', 'name' => 'Ntungu west', 'subcounty_id' => '80'],
            ['id' => '510', 'name' => 'Ntungu west', 'subcounty_id' => '179'],
            ['id' => '511', 'name' => 'Kava', 'subcounty_id' => '130'],
            ['id' => '512', 'name' => 'Kyahafu', 'subcounty_id' => '180'],
            ['id' => '513', 'name' => 'Kazindiro', 'subcounty_id' => '1'],
            ['id' => '514', 'name' => 'Bihanga', 'subcounty_id' => '159'],
            ['id' => '515', 'name' => 'Omuribere', 'subcounty_id' => '2'],
            ['id' => '516', 'name' => 'Kyamurire', 'subcounty_id' => '181'],
            ['id' => '517', 'name' => 'Bukongoro', 'subcounty_id' => '104'],
            ['id' => '518', 'name' => 'Kihanda', 'subcounty_id' => '182'],
            ['id' => '519', 'name' => 'Kashongorero', 'subcounty_id' => '126'],
            ['id' => '520', 'name' => 'Nyamiyaga', 'subcounty_id' => '21'],
            ['id' => '521', 'name' => 'Rushooza', 'subcounty_id' => '157'],
            ['id' => '522', 'name' => 'Rushooza', 'subcounty_id' => '183'],
            ['id' => '523', 'name' => 'Mahwizi', 'subcounty_id' => '104'],
            ['id' => '524', 'name' => 'Kitahurira', 'subcounty_id' => '107'],
            ['id' => '525', 'name' => 'Katojo', 'subcounty_id' => '49'],
            ['id' => '526', 'name' => 'Rushebeya', 'subcounty_id' => '50'],
            ['id' => '527', 'name' => 'Kisoro', 'subcounty_id' => '185'],
            ['id' => '528', 'name' => 'North ward', 'subcounty_id' => '185'],
            ['id' => '529', 'name' => 'Nagara', 'subcounty_id' => '71'],
            ['id' => '530', 'name' => 'Nagara', 'subcounty_id' => '186'],
            ['id' => '531', 'name' => 'Bujumiro', 'subcounty_id' => '187'],
            ['id' => '532', 'name' => 'Katenga', 'subcounty_id' => '174'],
            ['id' => '533', 'name' => 'Nyabubare', 'subcounty_id' => '163'],
            ['id' => '534', 'name' => 'Kicumbi', 'subcounty_id' => '174'],
            ['id' => '535', 'name' => 'Kanyarugiri', 'subcounty_id' => '159'],
            ['id' => '536', 'name' => 'Rurehe South', 'subcounty_id' => '68'],
            ['id' => '537', 'name' => 'Karubizi', 'subcounty_id' => '188'],
            ['id' => '538', 'name' => 'nyakatojo', 'subcounty_id' => '29'],
            ['id' => '539', 'name' => 'nyakatojo11', 'subcounty_id' => '29'],
            ['id' => '540', 'name' => 'Kanyamutwe', 'subcounty_id' => '2'],
            ['id' => '541', 'name' => 'Mutara', 'subcounty_id' => '8'],
            ['id' => '542', 'name' => 'Rukoni', 'subcounty_id' => '189'],
            ['id' => '543', 'name' => 'Nyarutuntu', 'subcounty_id' => '32'],
            ['id' => '544', 'name' => 'nyakatunguru', 'subcounty_id' => '39'],
            ['id' => '545', 'name' => 'Mukirwa', 'subcounty_id' => '137'],
            ['id' => '546', 'name' => 'Nyakishojwa', 'subcounty_id' => '101'],
            ['id' => '547', 'name' => 'Bitereko', 'subcounty_id' => '190'],
            ['id' => '548', 'name' => 'Kinoni Nyabihoko', 'subcounty_id' => '17'],
            ['id' => '549', 'name' => 'Bukala', 'subcounty_id' => '191'],
            ['id' => '550', 'name' => 'Kabuyanda', 'subcounty_id' => '192'],
            ['id' => '551', 'name' => 'Rwemiyonga', 'subcounty_id' => '78'],
            ['id' => '552', 'name' => 'Kyamukombe', 'subcounty_id' => '137'],
            ['id' => '553', 'name' => 'Nshebeya', 'subcounty_id' => '50'],
            ['id' => '554', 'name' => 'Ruborogota', 'subcounty_id' => '193'],
            ['id' => '555', 'name' => 'Kaharo', 'subcounty_id' => '67'],
            ['id' => '556', 'name' => 'Nyaja', 'subcounty_id' => '130'],
            ['id' => '557', 'name' => 'Kitojo', 'subcounty_id' => '1'],
            ['id' => '558', 'name' => 'Rwakabengo', 'subcounty_id' => '11'],
            ['id' => '559', 'name' => 'Karengyere', 'subcounty_id' => '49'],
            ['id' => '560', 'name' => 'Rwanyena', 'subcounty_id' => '157'],
            ['id' => '561', 'name' => 'Kichwamba', 'subcounty_id' => '195'],
            ['id' => '562', 'name' => 'Rubare', 'subcounty_id' => '62'],
            ['id' => '563', 'name' => 'Katuna', 'subcounty_id' => '14'],
            ['id' => '564', 'name' => 'Kashasha', 'subcounty_id' => '108'],
            ['id' => '565', 'name' => 'Kikoni', 'subcounty_id' => '139'],
            ['id' => '566', 'name' => 'Birambo', 'subcounty_id' => '130'],
            ['id' => '567', 'name' => 'Karangaro', 'subcounty_id' => '61'],
            ['id' => '568', 'name' => 'Kacerere', 'subcounty_id' => '88'],
            ['id' => '569', 'name' => 'kihanda', 'subcounty_id' => '39'],
            ['id' => '570', 'name' => 'Nothern Ward B', 'subcounty_id' => '10'],
            ['id' => '571', 'name' => 'Rwangunga', 'subcounty_id' => '193'],
            ['id' => '572', 'name' => 'Nyarurambi', 'subcounty_id' => '197'],
            ['id' => '573', 'name' => 'kyaruyenje', 'subcounty_id' => '5'],
            ['id' => '574', 'name' => 'Bukuba', 'subcounty_id' => '128'],
            ['id' => '575', 'name' => 'Sooka', 'subcounty_id' => '198'],
            ['id' => '576', 'name' => 'Nyakabungo', 'subcounty_id' => '107'],
            ['id' => '577', 'name' => 'Rushango', 'subcounty_id' => '159'],
            ['id' => '578', 'name' => 'Mugoma', 'subcounty_id' => '199'],
            ['id' => '579', 'name' => 'Kampala B', 'subcounty_id' => '142'],
            ['id' => '580', 'name' => 'Nyundo', 'subcounty_id' => '202'],
            ['id' => '581', 'name' => 'Rwamabondo T.B', 'subcounty_id' => '16'],
            ['id' => '582', 'name' => 'Mashongora', 'subcounty_id' => '7'],
            ['id' => '583', 'name' => 'Ntonwa', 'subcounty_id' => '203'],
            ['id' => '584', 'name' => 'Nyamiryango', 'subcounty_id' => '204'],
            ['id' => '585', 'name' => 'Kishuro', 'subcounty_id' => '101'],
            ['id' => '586', 'name' => 'Nothern Ward', 'subcounty_id' => '127'],
            ['id' => '587', 'name' => 'Butare', 'subcounty_id' => '164'],
            ['id' => '588', 'name' => 'Nyabubare', 'subcounty_id' => '140'],
            ['id' => '589', 'name' => 'Rubaga', 'subcounty_id' => '205'],
            ['id' => '590', 'name' => 'Ndorero', 'subcounty_id' => '61'],
            ['id' => '591', 'name' => 'nyarubale', 'subcounty_id' => '3'],
            ['id' => '592', 'name' => 'Mengo', 'subcounty_id' => '205'],
            ['id' => '593', 'name' => 'Buramba', 'subcounty_id' => '157'],
            ['id' => '594', 'name' => 'Bugongi', 'subcounty_id' => '39'],
            ['id' => '595', 'name' => 'Kanyinya', 'subcounty_id' => '11'],
            ['id' => '596', 'name' => 'Bwayegamba', 'subcounty_id' => '206'],
            ['id' => '597', 'name' => 'Burora', 'subcounty_id' => '3'],
            ['id' => '598', 'name' => 'Iterero', 'subcounty_id' => '175'],
            ['id' => '599', 'name' => 'Mboke', 'subcounty_id' => '207'],
            ['id' => '600', 'name' => 'mparo', 'subcounty_id' => '29'],
            ['id' => '601', 'name' => 'Karangara', 'subcounty_id' => '38'],
            ['id' => '602', 'name' => 'Kaberebere', 'subcounty_id' => '77'],
            ['id' => '603', 'name' => 'Kyera', 'subcounty_id' => '208'],
            ['id' => '604', 'name' => 'Kakabada Ward', 'subcounty_id' => '25'],
            ['id' => '605', 'name' => 'Kakabada Ward', 'subcounty_id' => '116'],
            ['id' => '606', 'name' => 'Ntungamo', 'subcounty_id' => '107'],
            ['id' => '607', 'name' => 'Gasovu', 'subcounty_id' => '209'],
            ['id' => '608', 'name' => 'Bushuro', 'subcounty_id' => '191'],
            ['id' => '609', 'name' => 'Buhozi', 'subcounty_id' => '210'],
            ['id' => '610', 'name' => 'Malere', 'subcounty_id' => '142'],
            ['id' => '611', 'name' => 'Kakigari', 'subcounty_id' => '115'],
            ['id' => '612', 'name' => 'Mirambiro', 'subcounty_id' => '163'],
            ['id' => '613', 'name' => 'Kyanzire', 'subcounty_id' => '128'],
            ['id' => '614', 'name' => 'Karyamenvu', 'subcounty_id' => '211'],
            ['id' => '615', 'name' => 'Kamuganguzi', 'subcounty_id' => '174'],
            ['id' => '616', 'name' => 'Rubingo', 'subcounty_id' => '196'],
            ['id' => '617', 'name' => 'Nteko', 'subcounty_id' => '212'],
            ['id' => '618', 'name' => 'Kiziba', 'subcounty_id' => '155'],
            ['id' => '619', 'name' => 'Kiziba', 'subcounty_id' => '214'],
            ['id' => '620', 'name' => 'Rubare', 'subcounty_id' => '21'],
            ['id' => '621', 'name' => 'Nyakashambya', 'subcounty_id' => '155'],
            ['id' => '622', 'name' => 'Esheshe', 'subcounty_id' => '215'],
            ['id' => '623', 'name' => 'Kirume', 'subcounty_id' => '216'],
            ['id' => '624', 'name' => 'Nshororo', 'subcounty_id' => '182'],
            ['id' => '625', 'name' => 'Bushwere', 'subcounty_id' => '78'],
            ['id' => '626', 'name' => 'Kalangala', 'subcounty_id' => '190'],
            ['id' => '627', 'name' => 'Nyamirama', 'subcounty_id' => '218'],
            ['id' => '628', 'name' => 'Kabere', 'subcounty_id' => '164'],
            ['id' => '629', 'name' => 'Kawaruju', 'subcounty_id' => '219'],
            ['id' => '630', 'name' => 'Ngoma', 'subcounty_id' => '20'],
            ['id' => '631', 'name' => 'Kitumba', 'subcounty_id' => '191'],
            ['id' => '632', 'name' => 'Nagaro ward', 'subcounty_id' => '50'],
            ['id' => '633', 'name' => 'Nangaro', 'subcounty_id' => '50'],
            ['id' => '634', 'name' => 'Nyaruhanga', 'subcounty_id' => '107'],
            ['id' => '635', 'name' => 'Bushura', 'subcounty_id' => '161'],
            ['id' => '636', 'name' => 'Iremera', 'subcounty_id' => '220'],
            ['id' => '637', 'name' => 'Kanyabitara Ward', 'subcounty_id' => '50'],
            ['id' => '638', 'name' => 'Nshaka', 'subcounty_id' => '188'],
            ['id' => '639', 'name' => 'Kakoni', 'subcounty_id' => '106'],
            ['id' => '640', 'name' => 'Rwambu', 'subcounty_id' => '223'],
            ['id' => '641', 'name' => 'Nyamweru', 'subcounty_id' => '71'],
            ['id' => '642', 'name' => 'Nkungu', 'subcounty_id' => '94'],
            ['id' => '643', 'name' => 'Isorora', 'subcounty_id' => '225'],
            ['id' => '644', 'name' => 'Kahama', 'subcounty_id' => '191'],
            ['id' => '645', 'name' => 'Nyakangogo', 'subcounty_id' => '175'],
            ['id' => '646', 'name' => 'Kyarwehunde', 'subcounty_id' => '32'],
            ['id' => '647', 'name' => 'Nyamabare', 'subcounty_id' => '101'],
            ['id' => '648', 'name' => 'Rubingo', 'subcounty_id' => '227'],
            ['id' => '649', 'name' => 'Rugarama', 'subcounty_id' => '128'],
            ['id' => '650', 'name' => 'Rwentango', 'subcounty_id' => '228'],
            ['id' => '651', 'name' => 'Kigyendwa', 'subcounty_id' => '229'],
            ['id' => '652', 'name' => 'Kyabinunga', 'subcounty_id' => '114'],
            ['id' => '653', 'name' => 'Kanyabwanga', 'subcounty_id' => '126'],
            ['id' => '654', 'name' => 'Mabona', 'subcounty_id' => '114'],
            ['id' => '655', 'name' => 'Nganiko', 'subcounty_id' => '230'],
            ['id' => '656', 'name' => 'Nyabubare', 'subcounty_id' => '175'],
            ['id' => '657', 'name' => 'Nyakishojwa', 'subcounty_id' => '120'],
            ['id' => '658', 'name' => 'Nakyenyi', 'subcounty_id' => '231'],
            ['id' => '659', 'name' => 'Kiyonga', 'subcounty_id' => '216'],
            ['id' => '660', 'name' => 'Kihihi', 'subcounty_id' => '80'],
            ['id' => '661', 'name' => 'Ngangi', 'subcounty_id' => '232'],
            ['id' => '662', 'name' => 'Rumuri', 'subcounty_id' => '153'],
            ['id' => '663', 'name' => 'Rumuri', 'subcounty_id' => '146'],
            ['id' => '664', 'name' => 'Muhanga Central Ward', 'subcounty_id' => '111'],
            ['id' => '665', 'name' => 'Kanyinya', 'subcounty_id' => '61'],
            ['id' => '666', 'name' => 'Rutooma', 'subcounty_id' => '68'],
            ['id' => '667', 'name' => 'Ruhiira', 'subcounty_id' => '80'],
            ['id' => '668', 'name' => 'Bukora', 'subcounty_id' => '191'],
            ['id' => '669', 'name' => 'kasozi', 'subcounty_id' => '236'],
            ['id' => '670', 'name' => 'Kibaasi', 'subcounty_id' => '237'],
            ['id' => '671', 'name' => 'Kanyambeho', 'subcounty_id' => '188'],
            ['id' => '672', 'name' => 'Kagari', 'subcounty_id' => '127'],
            ['id' => '673', 'name' => 'Ngomba Buremba', 'subcounty_id' => '106'],
            ['id' => '674', 'name' => 'Nsangi', 'subcounty_id' => '240'],
            ['id' => '675', 'name' => 'Kyabandara ward', 'subcounty_id' => '156'],
            ['id' => '676', 'name' => 'Ntundu', 'subcounty_id' => '118'],
            ['id' => '677', 'name' => 'Ruhonwa', 'subcounty_id' => '50'],
            ['id' => '678', 'name' => 'Kyabihwa', 'subcounty_id' => '242'],
            ['id' => '679', 'name' => 'Kitoma', 'subcounty_id' => '183'],
            ['id' => '680', 'name' => 'Rusheka', 'subcounty_id' => '118'],
            ['id' => '681', 'name' => 'Nyakigyera', 'subcounty_id' => '113'],
            ['id' => '682', 'name' => 'Karengyere', 'subcounty_id' => '164'],
            ['id' => '683', 'name' => 'kabasheshe', 'subcounty_id' => '42'],
            ['id' => '684', 'name' => 'kabasheshe', 'subcounty_id' => '243'],
            ['id' => '685', 'name' => 'sweswe', 'subcounty_id' => '244'],
            ['id' => '686', 'name' => 'Rukarango', 'subcounty_id' => '15'],
            ['id' => '687', 'name' => 'Kakoma', 'subcounty_id' => '158'],
            ['id' => '688', 'name' => 'Kakika', 'subcounty_id' => '14'],
            ['id' => '689', 'name' => 'Igayaza', 'subcounty_id' => '245'],
            ['id' => '690', 'name' => 'Kinoni', 'subcounty_id' => '17'],
            ['id' => '691', 'name' => 'Kijungu', 'subcounty_id' => '246'],
            ['id' => '692', 'name' => 'Sweswe', 'subcounty_id' => '241'],
            ['id' => '693', 'name' => 'Kabaare', 'subcounty_id' => '144'],
            ['id' => '694', 'name' => 'kamakoma', 'subcounty_id' => '137'],
            ['id' => '695', 'name' => 'Kabweza', 'subcounty_id' => '244'],
            ['id' => '696', 'name' => 'Kabimbiri', 'subcounty_id' => '35'],
            ['id' => '697', 'name' => 'Mabona Ward', 'subcounty_id' => '247'],
            ['id' => '698', 'name' => 'Gasiza', 'subcounty_id' => '213'],
            ['id' => '699', 'name' => 'Kigabagaba', 'subcounty_id' => '127'],
            ['id' => '700', 'name' => 'Nyakitoko', 'subcounty_id' => '249'],
            ['id' => '701', 'name' => 'Kekubo', 'subcounty_id' => '250'],
            ['id' => '702', 'name' => 'Rwanda', 'subcounty_id' => '175'],
            ['id' => '703', 'name' => 'Kagunga', 'subcounty_id' => '200'],
            ['id' => '704', 'name' => 'Mujunju', 'subcounty_id' => '251'],
            ['id' => '705', 'name' => 'Kasheregyenyi', 'subcounty_id' => '174'],
            ['id' => '706', 'name' => 'Kyempene', 'subcounty_id' => '134'],
            ['id' => '707', 'name' => 'Kyempene', 'subcounty_id' => '18'],
            ['id' => '708', 'name' => 'Ruti', 'subcounty_id' => '252'],
            ['id' => '709', 'name' => 'Kanyamatembe', 'subcounty_id' => '137'],
            ['id' => '710', 'name' => 'Kiziba', 'subcounty_id' => '253'],
            ['id' => '711', 'name' => 'Migyera', 'subcounty_id' => '80'],
            ['id' => '712', 'name' => 'Nyamabare', 'subcounty_id' => '108'],
            ['id' => '713', 'name' => 'Rugongi', 'subcounty_id' => '256'],
            ['id' => '714', 'name' => 'Kipisi', 'subcounty_id' => '257'],
            ['id' => '715', 'name' => 'Katabushera', 'subcounty_id' => '13'],
            ['id' => '716', 'name' => 'Nyanga', 'subcounty_id' => '95'],
            ['id' => '717', 'name' => 'Ngangi', 'subcounty_id' => '90'],
            ['id' => '718', 'name' => 'Kakore', 'subcounty_id' => '50'],
            ['id' => '719', 'name' => 'Birongo', 'subcounty_id' => '236'],
            ['id' => '720', 'name' => 'Nyakabare', 'subcounty_id' => '14'],
            ['id' => '721', 'name' => 'Kakibaya', 'subcounty_id' => '2'],
            ['id' => '722', 'name' => 'Rwanja East', 'subcounty_id' => '56'],
            ['id' => '723', 'name' => 'Muganza', 'subcounty_id' => '258'],
            ['id' => '724', 'name' => 'Kamuhanga', 'subcounty_id' => '58'],
            ['id' => '725', 'name' => 'Mirimbi', 'subcounty_id' => '259'],
            ['id' => '726', 'name' => 'Kahunga', 'subcounty_id' => '196'],
            ['id' => '727', 'name' => 'Kahunga', 'subcounty_id' => '139'],
            ['id' => '728', 'name' => 'Nyamuyanja', 'subcounty_id' => '229'],
            ['id' => '729', 'name' => 'Kongoro', 'subcounty_id' => '115'],
            ['id' => '730', 'name' => 'Omukatojo', 'subcounty_id' => '182'],
            ['id' => '731', 'name' => 'Iremere', 'subcounty_id' => '220'],
            ['id' => '732', 'name' => 'Bukimbiri', 'subcounty_id' => '260'],
            ['id' => '733', 'name' => 'Burora', 'subcounty_id' => '48'],
            ['id' => '734', 'name' => 'Mpererwe', 'subcounty_id' => '262'],
            ['id' => '735', 'name' => 'Butiiti', 'subcounty_id' => '263'],
            ['id' => '736', 'name' => 'Kagoragaro', 'subcounty_id' => '75'],
            ['id' => '737', 'name' => 'Karagaro', 'subcounty_id' => '61'],
            ['id' => '738', 'name' => 'Karagaro', 'subcounty_id' => '81'],
            ['id' => '739', 'name' => 'Rutete', 'subcounty_id' => '264'],
            ['id' => '740', 'name' => 'Rubirizi', 'subcounty_id' => '104'],
            ['id' => '741', 'name' => 'Mirongo', 'subcounty_id' => '266'],
            ['id' => '742', 'name' => 'Mirongo', 'subcounty_id' => '267'],
            ['id' => '743', 'name' => 'Kazawu', 'subcounty_id' => '118'],
            ['id' => '744', 'name' => 'Kafunjo', 'subcounty_id' => '37'],
            ['id' => '745', 'name' => 'Rubengye', 'subcounty_id' => '249'],
            ['id' => '746', 'name' => 'Karangaro Ward', 'subcounty_id' => '116'],
            ['id' => '747', 'name' => 'Kitojo', 'subcounty_id' => '34'],
            ['id' => '748', 'name' => 'Kitojo', 'subcounty_id' => '270'],
            ['id' => '749', 'name' => 'Rutaare', 'subcounty_id' => '258'],
            ['id' => '750', 'name' => 'Magondo', 'subcounty_id' => '271'],
            ['id' => '751', 'name' => 'Kashozi', 'subcounty_id' => '257'],
            ['id' => '752', 'name' => 'Kashozi', 'subcounty_id' => '272'],
            ['id' => '753', 'name' => 'Ryamarembo', 'subcounty_id' => '273'],
            ['id' => '754', 'name' => 'Komamboga', 'subcounty_id' => '274'],
            ['id' => '755', 'name' => 'Mwogyera', 'subcounty_id' => '218'],
            ['id' => '756', 'name' => 'Rwamahamba', 'subcounty_id' => '188'],
            ['id' => '757', 'name' => 'Mayengo', 'subcounty_id' => '174'],
            ['id' => '758', 'name' => 'Kyabahesi', 'subcounty_id' => '182'],
            ['id' => '759', 'name' => 'Kitunga', 'subcounty_id' => '17'],
            ['id' => '760', 'name' => 'Kyabahura', 'subcounty_id' => '106'],
            ['id' => '761', 'name' => 'Buharambo', 'subcounty_id' => '60'],
            ['id' => '762', 'name' => 'Omurubirizi', 'subcounty_id' => '21'],
            ['id' => '763', 'name' => 'Kamubizi', 'subcounty_id' => '80'],
            ['id' => '764', 'name' => 'Bwayegaba', 'subcounty_id' => '206']
        ];

        foreach ($parishes AS $parish):
            Parish::firstOrCreate([
                "id" => $parish["id"],
                "name" => $parish["name"],
                "subcounty_id" => $parish["subcounty_id"]
            ]);
        endforeach;
    }
}
