<?php

use Illuminate\Database\Seeder;
use App\Subcounty;

class SubCountiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subcounties = [
            ['id' => '1', 'name' => 'Buyanja', 'county_id' => '1'],
            ['id' => '2', 'name' => 'Kebisoni', 'county_id' => '1'],
            ['id' => '3', 'name' => 'Nyakishenyi', 'county_id' => '1'],
            ['id' => '4', 'name' => 'Nyarushanje', 'county_id' => '1'],
            ['id' => '5', 'name' => 'Buhunga', 'county_id' => '2'],
            ['id' => '6', 'name' => 'Bwambara', 'county_id' => '2'],
            ['id' => '7', 'name' => 'Nyakagyeme', 'county_id' => '2'],
            ['id' => '8', 'name' => 'Ruhinda', 'county_id' => '2'],
            ['id' => '9', 'name' => 'Eastern Ward', 'county_id' => '3'],
            ['id' => '10', 'name' => 'Eastern Ward.', 'county_id' => '3'],
            ['id' => '11', 'name' => 'Ruk. Southern Division', 'county_id' => '3'],
            ['id' => '12', 'name' => 'Ruk. Western Division', 'county_id' => '3'],
            ['id' => '13', 'name' => 'Bugangari', 'county_id' => '2'],
            ['id' => '14', 'name' => 'Bwongyera', 'county_id' => '4'],
            ['id' => '15', 'name' => 'Ihunga', 'county_id' => '4'],
            ['id' => '16', 'name' => 'Kibatsi', 'county_id' => '4'],
            ['id' => '17', 'name' => 'Nyabihoko', 'county_id' => '4'],
            ['id' => '18', 'name' => 'Rugarama', 'county_id' => '6'],
            ['id' => '19', 'name' => 'Central Division', 'county_id' => '7'],
            ['id' => '20', 'name' => 'Ngoma', 'county_id' => '6'],
            ['id' => '21', 'name' => 'Rubaare', 'county_id' => '6'],
            ['id' => '22', 'name' => 'Eastern Division', 'county_id' => '7'],
            ['id' => '23', 'name' => 'Western Division', 'county_id' => '7'],
            ['id' => '24', 'name' => 'Southern Division', 'county_id' => '9'],
            ['id' => '25', 'name' => 'Northern Division', 'county_id' => '9'],
            ['id' => '26', 'name' => 'Central Division Kabale', 'county_id' => '9'],
            ['id' => '27', 'name' => 'Bukinda', 'county_id' => '8'],
            ['id' => '28', 'name' => 'Kamwezi', 'county_id' => '8'],
            ['id' => '29', 'name' => 'Kashambya', 'county_id' => '8'],
            ['id' => '30', 'name' => 'Rwamucucu', 'county_id' => '8'],
            ['id' => '31', 'name' => 'Itojo', 'county_id' => '5'],
            ['id' => '32', 'name' => 'Ntungamo', 'county_id' => '5'],
            ['id' => '33', 'name' => 'Nyakyera', 'county_id' => '5'],
            ['id' => '34', 'name' => 'Ruhaama', 'county_id' => '5'],
            ['id' => '35', 'name' => 'Rukoni East', 'county_id' => '5'],
            ['id' => '36', 'name' => 'Rukoni West', 'county_id' => '5'],
            ['id' => '37', 'name' => 'Rweikiniro', 'county_id' => '5'],
            ['id' => '38', 'name' => 'Kayonza', 'county_id' => '6'],
            ['id' => '39', 'name' => 'Kambuga', 'county_id' => '12'],
            ['id' => '40', 'name' => 'Kanungu T/C', 'county_id' => '12'],
            ['id' => '41', 'name' => 'Kanyantorogo', 'county_id' => '12'],
            ['id' => '42', 'name' => 'Kayonza.', 'county_id' => '12'],
            ['id' => '43', 'name' => 'Kihihi', 'county_id' => '12'],
            ['id' => '44', 'name' => 'Kihihi T/C', 'county_id' => '12'],
            ['id' => '45', 'name' => 'Kirima', 'county_id' => '12'],
            ['id' => '46', 'name' => 'Mpungu', 'county_id' => '12'],
            ['id' => '47', 'name' => 'Nyamirama', 'county_id' => '12'],
            ['id' => '48', 'name' => 'Rugyeyo', 'county_id' => '12'],
            ['id' => '49', 'name' => 'Rutenga', 'county_id' => '12'],
            ['id' => '50', 'name' => 'Hamurwa', 'county_id' => '10'],
            ['id' => '51', 'name' => 'KATUNGAMO', 'county_id' => '6'],
            ['id' => '52', 'name' => 'KINAMO', 'county_id' => '18'],
            ['id' => '53', 'name' => 'Ibaare', 'county_id' => '19'],
            ['id' => '54', 'name' => 'Ruhija', 'county_id' => '10'],
            ['id' => '55', 'name' => 'Endeinzi', 'county_id' => '20'],
            ['id' => '56', 'name' => 'MAYANGA', 'county_id' => '21'],
            ['id' => '57', 'name' => 'Kayurwe', 'county_id' => '14'],
            ['id' => '58', 'name' => 'Nyakashebeya', 'county_id' => '22'],
            ['id' => '59', 'name' => 'KABIRA', 'county_id' => '9'],
            ['id' => '60', 'name' => 'kabira', 'county_id' => '23'],
            ['id' => '61', 'name' => 'kagunga', 'county_id' => '3'],
            ['id' => '62', 'name' => 'Rubare', 'county_id' => '13'],
            ['id' => '63', 'name' => 'Ngomba', 'county_id' => '24'],
            ['id' => '64', 'name' => 'Bukinda', 'county_id' => '11'],
            ['id' => '65', 'name' => 'Kitwe Town council', 'county_id' => '5'],
            ['id' => '66', 'name' => 'Rugarama', 'county_id' => '24'],
            ['id' => '67', 'name' => 'Kaharo', 'county_id' => '11'],
            ['id' => '68', 'name' => 'RUREHE', 'county_id' => '21'],
            ['id' => '69', 'name' => 'Kyanamira', 'county_id' => '11'],
            ['id' => '70', 'name' => 'Busiriba', 'county_id' => '26'],
            ['id' => '71', 'name' => 'Nyamweru', 'county_id' => '10'],
            ['id' => '72', 'name' => 'RUKIGA', 'county_id' => '8'],
            ['id' => '73', 'name' => 'Bubaare', 'county_id' => '10'],
            ['id' => '74', 'name' => 'RUKUNGIRI MUNICIPALITY', 'county_id' => '28'],
            ['id' => '75', 'name' => 'KAGUNGA', 'county_id' => '28'],
            ['id' => '76', 'name' => 'Buhara', 'county_id' => '11'],
            ['id' => '77', 'name' => 'Nkoma', 'county_id' => '30'],
            ['id' => '78', 'name' => 'Mwizi', 'county_id' => '31'],
            ['id' => '79', 'name' => 'Katuna town council', 'county_id' => '11'],
            ['id' => '80', 'name' => 'Nyakitunda', 'county_id' => '32'],
            ['id' => '81', 'name' => 'Kagunga', 'county_id' => '2'],
            ['id' => '82', 'name' => 'Kinuka', 'county_id' => '33'],
            ['id' => '83', 'name' => 'Katojo', 'county_id' => '12'],
            ['id' => '84', 'name' => 'kitwe', 'county_id' => '36'],
            ['id' => '85', 'name' => 'ruhama', 'county_id' => '36'],
            ['id' => '86', 'name' => 'Kitwe Tc', 'county_id' => '35'],
            ['id' => '87', 'name' => 'Engaju', 'county_id' => '37'],
            ['id' => '88', 'name' => 'Bufundi', 'county_id' => '10'],
            ['id' => '89', 'name' => 'Katenga', 'county_id' => '21'],
            ['id' => '90', 'name' => 'Rwentuha', 'county_id' => '38'],
            ['id' => '91', 'name' => 'Rwentuha', 'county_id' => '39'],
            ['id' => '92', 'name' => 'Bweza', 'county_id' => '40'],
            ['id' => '93', 'name' => 'Kitura', 'county_id' => '40'],
            ['id' => '94', 'name' => 'Nkungu', 'county_id' => '41'],
            ['id' => '95', 'name' => 'Nyanga', 'county_id' => '12'],
            ['id' => '96', 'name' => 'Butogota TC', 'county_id' => '12'],
            ['id' => '97', 'name' => 'NYAKINAMA', 'county_id' => '42'],
            ['id' => '98', 'name' => 'Kasagama', 'county_id' => '44'],
            ['id' => '99', 'name' => 'Karucumisi', 'county_id' => '45'],
            ['id' => '100', 'name' => 'Western ward', 'county_id' => '45'],
            ['id' => '101', 'name' => 'Katete', 'county_id' => '12'],
            ['id' => '102', 'name' => 'Rwntobo', 'county_id' => '6'],
            ['id' => '103', 'name' => 'Kigando', 'county_id' => '46'],
            ['id' => '104', 'name' => 'Mutara', 'county_id' => '21'],
            ['id' => '105', 'name' => 'mijwala', 'county_id' => '47'],
            ['id' => '106', 'name' => 'Buremba', 'county_id' => '41'],
            ['id' => '107', 'name' => 'Ikumba', 'county_id' => '10'],
            ['id' => '108', 'name' => 'RUbanda', 'county_id' => '10'],
            ['id' => '109', 'name' => 'Ikumba 1', 'county_id' => '10'],
            ['id' => '110', 'name' => 'Nyaruhanga', 'county_id' => '10'],
            ['id' => '111', 'name' => 'Muhanga Town Council', 'county_id' => '8'],
            ['id' => '112', 'name' => 'Kashangura', 'county_id' => '49'],
            ['id' => '113', 'name' => 'Kabingo', 'county_id' => '32'],
            ['id' => '114', 'name' => 'Kabingo', 'county_id' => '32'],
            ['id' => '115', 'name' => 'Ndiija', 'county_id' => '31'],
            ['id' => '116', 'name' => 'Rukungiri Nothern Ward', 'county_id' => '3'],
            ['id' => '117', 'name' => 'Kiyanga', 'county_id' => '21'],
            ['id' => '118', 'name' => 'Kikagate', 'county_id' => '32'],
            ['id' => '119', 'name' => 'Kasozi', 'county_id' => '50'],
            ['id' => '120', 'name' => 'Mushunga', 'county_id' => '21'],
            ['id' => '121', 'name' => 'Mushunga', 'county_id' => '21'],
            ['id' => '122', 'name' => 'RWASHAMIRE TC', 'county_id' => '4'],
            ['id' => '123', 'name' => 'Kagongi', 'county_id' => '45'],
            ['id' => '124', 'name' => 'Kagongi', 'county_id' => '45'],
            ['id' => '125', 'name' => 'Kagongi', 'county_id' => '45'],
            ['id' => '126', 'name' => 'kanyabwanga', 'county_id' => '21'],
            ['id' => '127', 'name' => 'Kabuyanda', 'county_id' => '32'],
            ['id' => '128', 'name' => 'Kashenshero', 'county_id' => '21'],
            ['id' => '129', 'name' => 'Kitagata', 'county_id' => '50'],
            ['id' => '130', 'name' => 'Maziba', 'county_id' => '11'],
            ['id' => '131', 'name' => 'Kicwamba', 'county_id' => '51'],
            ['id' => '132', 'name' => 'Muhorro TC', 'county_id' => '52'],
            ['id' => '133', 'name' => 'Rutoto', 'county_id' => '51'],
            ['id' => '134', 'name' => 'Rugarama', 'county_id' => '13'],
            ['id' => '135', 'name' => 'Kitojo', 'county_id' => '59'],
            ['id' => '136', 'name' => 'Rwamucucu', 'county_id' => '59'],
            ['id' => '137', 'name' => 'Kinaba', 'county_id' => '12'],
            ['id' => '138', 'name' => 'Ihunga', 'county_id' => '61'],
            ['id' => '139', 'name' => 'Kahunga', 'county_id' => '5'],
            ['id' => '140', 'name' => 'kabira', 'county_id' => '21'],
            ['id' => '141', 'name' => 'Nyamasa', 'county_id' => '52'],
            ['id' => '142', 'name' => 'Biguri', 'county_id' => '30'],
            ['id' => '143', 'name' => 'Rwamucucu', 'county_id' => '58'],
            ['id' => '144', 'name' => 'Ngarama', 'county_id' => '20'],
            ['id' => '145', 'name' => 'Magambo', 'county_id' => '51'],
            ['id' => '146', 'name' => 'kichwamba', 'county_id' => '63'],
            ['id' => '147', 'name' => 'Kakoba', 'county_id' => '65'],
            ['id' => '148', 'name' => 'Engari', 'county_id' => '41'],
            ['id' => '149', 'name' => 'Kikyenkye', 'county_id' => '49'],
            ['id' => '150', 'name' => 'Ruyonza', 'county_id' => '39'],
            ['id' => '151', 'name' => 'Kachera', 'county_id' => '66'],
            ['id' => '152', 'name' => 'Kahunge', 'county_id' => '30'],
            ['id' => '153', 'name' => 'Kichwamba', 'county_id' => '51'],
            ['id' => '154', 'name' => 'kichwamba', 'county_id' => '53'],
            ['id' => '155', 'name' => 'Kagango', 'county_id' => '68'],
            ['id' => '156', 'name' => 'SHEEMA', 'county_id' => '68'],
            ['id' => '157', 'name' => 'Rubaya', 'county_id' => '11'],
            ['id' => '158', 'name' => 'Rwemiyaga', 'county_id' => '69'],
            ['id' => '159', 'name' => 'Nyamarebe', 'county_id' => '49'],
            ['id' => '160', 'name' => 'Nyamarebe', 'county_id' => '49'],
            ['id' => '161', 'name' => 'bubare', 'county_id' => '10'],
            ['id' => '162', 'name' => 'Kashenyi', 'county_id' => '10'],
            ['id' => '163', 'name' => 'Rushasha', 'county_id' => '20'],
            ['id' => '164', 'name' => 'Muko', 'county_id' => '10'],
            ['id' => '165', 'name' => 'Kakabara', 'county_id' => '39'],
            ['id' => '166', 'name' => 'Kanoni', 'county_id' => '41'],
            ['id' => '167', 'name' => 'Kagarama', 'county_id' => '3'],
            ['id' => '168', 'name' => 'Rugandu', 'county_id' => '31'],
            ['id' => '169', 'name' => 'Rugaga', 'county_id' => '20'],
            ['id' => '170', 'name' => 'kankoma', 'county_id' => '3'],
            ['id' => '171', 'name' => 'Entusi', 'county_id' => '47'],
            ['id' => '172', 'name' => 'kamukuzi', 'county_id' => '65'],
            ['id' => '173', 'name' => 'Kyeizooba', 'county_id' => '72'],
            ['id' => '174', 'name' => 'Kamunganguzi', 'county_id' => '11'],
            ['id' => '175', 'name' => 'Bwongyera', 'county_id' => '61'],
            ['id' => '176', 'name' => 'Keyembe', 'county_id' => '73'],
            ['id' => '177', 'name' => 'Kazo TC', 'county_id' => '41'],
            ['id' => '178', 'name' => 'Kagarama town council', 'county_id' => '4'],
            ['id' => '179', 'name' => 'Nyakitunda', 'county_id' => '20'],
            ['id' => '180', 'name' => 'Murora', 'county_id' => '42'],
            ['id' => '181', 'name' => 'Bugongi', 'county_id' => '50'],
            ['id' => '182', 'name' => 'Mbaare', 'county_id' => '20'],
            ['id' => '183', 'name' => 'Rubaya', 'county_id' => '45'],
            ['id' => '184', 'name' => 'Rutenga', 'county_id' => '14'],
            ['id' => '185', 'name' => 'Kisoro Municipality', 'county_id' => '75'],
            ['id' => '186', 'name' => 'Nyamwiru', 'county_id' => '10'],
            ['id' => '187', 'name' => 'Buhanda', 'county_id' => '77'],
            ['id' => '188', 'name' => 'Nyakinoni', 'county_id' => '12'],
            ['id' => '189', 'name' => 'Kibasi', 'county_id' => '61'],
            ['id' => '190', 'name' => 'Bitereko', 'county_id' => '21'],
            ['id' => '191', 'name' => 'Kitumba', 'county_id' => '11'],
            ['id' => '192', 'name' => 'Kigabagaba', 'county_id' => '32'],
            ['id' => '193', 'name' => 'Ruborogota', 'county_id' => '32'],
            ['id' => '194', 'name' => 'Southern Division', 'county_id' => '2'],
            ['id' => '195', 'name' => 'Ntara', 'county_id' => '78'],
            ['id' => '196', 'name' => 'Kahunga', 'county_id' => '35'],
            ['id' => '197', 'name' => 'Kabirizi', 'county_id' => '10'],
            ['id' => '198', 'name' => 'Muramba', 'county_id' => '42'],
            ['id' => '199', 'name' => 'Nyabuharwa', 'county_id' => '79'],
            ['id' => '200', 'name' => 'Bufundi- Rubanda', 'county_id' => '10'],
            ['id' => '201', 'name' => 'Bufundi', 'county_id' => '73'],
            ['id' => '202', 'name' => 'Nyundo', 'county_id' => '42'],
            ['id' => '203', 'name' => 'Bwizi', 'county_id' => '30'],
            ['id' => '204', 'name' => 'Butanda', 'county_id' => '11'],
            ['id' => '205', 'name' => 'Rubaga Division', 'county_id' => '80'],
            ['id' => '206', 'name' => 'Kigarama', 'county_id' => '68'],
            ['id' => '207', 'name' => 'Angweti Angweti', 'county_id' => '81'],
            ['id' => '208', 'name' => 'Birere', 'county_id' => '32'],
            ['id' => '209', 'name' => 'Nyarusiza', 'county_id' => '42'],
            ['id' => '210', 'name' => 'Busaza', 'county_id' => '82'],
            ['id' => '211', 'name' => 'Kashagama', 'county_id' => '83'],
            ['id' => '212', 'name' => 'Nyabwishenya', 'county_id' => '42'],
            ['id' => '213', 'name' => 'Kisoro Town', 'county_id' => '42'],
            ['id' => '214', 'name' => 'Kagango', 'county_id' => '50'],
            ['id' => '215', 'name' => 'Omugari', 'county_id' => '41'],
            ['id' => '216', 'name' => 'Kigando', 'county_id' => '84'],
            ['id' => '217', 'name' => 'Nansana', 'county_id' => '34'],
            ['id' => '218', 'name' => 'Katerera', 'county_id' => '85'],
            ['id' => '219', 'name' => 'Kihura', 'county_id' => '79'],
            ['id' => '220', 'name' => 'Bukimbiri', 'county_id' => '86'],
            ['id' => '221', 'name' => 'Nyabubare', 'county_id' => '72'],
            ['id' => '222', 'name' => 'Bubare', 'county_id' => '70'],
            ['id' => '223', 'name' => 'Kizongo', 'county_id' => '49'],
            ['id' => '224', 'name' => 'Isorora', 'county_id' => '86'],
            ['id' => '225', 'name' => 'Nyakabande', 'county_id' => '86'],
            ['id' => '226', 'name' => 'Rukungiri', 'county_id' => '3'],
            ['id' => '227', 'name' => 'Karambi', 'county_id' => '87'],
            ['id' => '228', 'name' => 'Nyarubungo', 'county_id' => '32'],
            ['id' => '229', 'name' => 'Nyamuyanja', 'county_id' => '32'],
            ['id' => '230', 'name' => 'Nyabani', 'county_id' => '78'],
            ['id' => '231', 'name' => 'Nakyenyi', 'county_id' => '88'],
            ['id' => '232', 'name' => 'Kasule', 'county_id' => '39'],
            ['id' => '233', 'name' => 'Moko', 'county_id' => '10'],
            ['id' => '234', 'name' => 'Muuko', 'county_id' => '10'],
            ['id' => '235', 'name' => 'Nyarurambi', 'county_id' => '10'],
            ['id' => '236', 'name' => 'Ishongororo', 'county_id' => '49'],
            ['id' => '237', 'name' => 'Hakibale', 'county_id' => '87'],
            ['id' => '238', 'name' => 'Kitunga', 'county_id' => '84'],
            ['id' => '239', 'name' => 'Bureba', 'county_id' => '41'],
            ['id' => '240', 'name' => 'Nsangi', 'county_id' => '90'],
            ['id' => '241', 'name' => 'Kabweza', 'county_id' => '39'],
            ['id' => '242', 'name' => 'Kibanda', 'county_id' => '66'],
            ['id' => '243', 'name' => 'kayonza', 'county_id' => '4'],
            ['id' => '244', 'name' => 'kyegegwa', 'county_id' => '39'],
            ['id' => '245', 'name' => 'Irembo', 'county_id' => '91'],
            ['id' => '246', 'name' => 'Bihanga', 'county_id' => '92'],
            ['id' => '247', 'name' => 'Isingiro T/C', 'county_id' => '32'],
            ['id' => '248', 'name' => 'Nyakitoko', 'county_id' => '93'],
            ['id' => '249', 'name' => 'Burere', 'county_id' => '93'],
            ['id' => '250', 'name' => 'Kanara', 'county_id' => '78'],
            ['id' => '251', 'name' => 'Kibito', 'county_id' => '94'],
            ['id' => '252', 'name' => 'Nyamitanga', 'county_id' => '65'],
            ['id' => '253', 'name' => 'Kamwenge', 'county_id' => '92'],
            ['id' => '254', 'name' => 'Rushere', 'county_id' => '95'],
            ['id' => '255', 'name' => 'Rushere', 'county_id' => '96'],
            ['id' => '256', 'name' => 'Nyakasharara', 'county_id' => '96'],
            ['id' => '257', 'name' => 'Shuku', 'county_id' => '50'],
            ['id' => '258', 'name' => 'Chahi', 'county_id' => '42'],
            ['id' => '259', 'name' => 'Kyembogo', 'county_id' => '79'],
            ['id' => '260', 'name' => 'Iremera', 'county_id' => '98'],
            ['id' => '261', 'name' => 'Bukimbiri', 'county_id' => '98'],
            ['id' => '262', 'name' => 'Itulla', 'county_id' => '99'],
            ['id' => '263', 'name' => 'Butiiti', 'county_id' => '79'],
            ['id' => '264', 'name' => 'Buyanga West', 'county_id' => '100'],
            ['id' => '265', 'name' => 'Shunga', 'county_id' => '12'],
            ['id' => '266', 'name' => 'Kashare', 'county_id' => '101'],
            ['id' => '267', 'name' => 'Kashare', 'county_id' => '45'],
            ['id' => '268', 'name' => 'Mirongo', 'county_id' => '45'],
            ['id' => '269', 'name' => 'Burere', 'county_id' => '37'],
            ['id' => '270', 'name' => 'Kihanga', 'county_id' => '5'],
            ['id' => '271', 'name' => 'Burunga', 'county_id' => '41'],
            ['id' => '272', 'name' => 'Shuku', 'county_id' => '68'],
            ['id' => '273', 'name' => 'kyamuhunga', 'county_id' => '103'],
            ['id' => '274', 'name' => 'Kawempe Division', 'county_id' => '99']
        ];

        foreach ($subcounties as $subcounty):
            Subcounty::firstOrCreate([
                "id" => $subcounty["id"],
                "name" => $subcounty["name"],
                "county_id" => $subcounty["county_id"]
            ]);
        endforeach;
    }
}
